name: librebooking

services:
  db:
    image: linuxserver/mariadb:10.6.13
    restart: always
    volumes:
      - db_conf:/config
    env_file:
      - db.env
    networks:
      - default
  app:
    image: librebooking/librebooking:4.0.0
    restart: always
    depends_on:
      - db
    volumes:
      - app_conf:/config  
      - ../uploads/images:/var/www/html/Web/uploads/images
      - ../uploads/reservation:/var/www/html/Web/uploads/reservation
    env_file:
      - lb.env
    networks:
      - default
      - dokploy-network
  cron:
    image: librebooking/librebooking:4.0.0
    restart: always
    user: root
    entrypoint: /usr/local/bin/cron.sh
    depends_on:
      - app
    volumes:
      - app_conf:/config
    env_file:
      - lb.env

volumes:
  db_conf:
  app_conf:
networks:
  dokploy-network:
    external: true
